### ISSUE TITLE
name 'args' is not defined

### ISSUE THREAD

**Issue by Atndesign** [Harmonai-org/sample-generator#3]
When trying to create the model, I can't seem to make it work, there is the following message: name 'args' is not defined
![image](https://user-images.githubusercontent.com/30182961/191628204-da07031c-c9d0-4994-a0be-de47538f5da9.png)

**Comment by Jorghi12** [comment]
Hi! You might've missed running one of the earlier portions of the jupyter notebook. For instance, args should be defined much earlier inside the notebook here

```
class Object(object):
    pass

args = Object()
args.sample_size = sample_size
args.sample_rate = sample_rate
args.latent_dim = latent_dim
```

**Comment by twobob** [comment]
This is the correct analysis
