### ISSUE TITLE
VRAM requirements?

### ISSUE THREAD

**Issue by illtellyoulater** [Harmonai-org/sample-generator#5]
How much VRAM does it need for either training or just inference?

**Comment by Jorghi12** [comment]
Hi! It depends on the model you use. There exists the following:

```
glitch-440k
jmann-small-190k
jmann-large-580k
maestro-150k
unlocked-250k
honk-140k
```

In general, you want enough VRAM to load the model weights (e.g. the checkpoints above) + the model architecture itself. 1GB VRAM should be enough to handle both the training and inference of these models.

**Comment by twobob** [comment]
16Gb VRAM should get you going for the training. 
8gb maybe for a small inference job.

**Comment by illtellyoulater** [comment]
I see, thanks.
Do you think with some optimization the VRAM required for training could be lowered to about 10-12 GB?
